// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/signal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalFilter struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignalTypes       []string               `protobuf:"bytes,1,rep,name=signal_types,json=signalTypes,proto3" json:"signal_types,omitempty"`
	SourceChains      []string               `protobuf:"bytes,2,rep,name=source_chains,json=sourceChains,proto3" json:"source_chains,omitempty"`
	DestinationChains []string               `protobuf:"bytes,3,rep,name=destination_chains,json=destinationChains,proto3" json:"destination_chains,omitempty"`
	Tokens            []string               `protobuf:"bytes,4,rep,name=tokens,proto3" json:"tokens,omitempty"`
	MinConfidence     float64                `protobuf:"fixed64,5,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SignalFilter) Reset() {
	*x = SignalFilter{}
	mi := &file_proto_signal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalFilter) ProtoMessage() {}

func (x *SignalFilter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalFilter.ProtoReflect.Descriptor instead.
func (*SignalFilter) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{0}
}

func (x *SignalFilter) GetSignalTypes() []string {
	if x != nil {
		return x.SignalTypes
	}
	return nil
}

func (x *SignalFilter) GetSourceChains() []string {
	if x != nil {
		return x.SourceChains
	}
	return nil
}

func (x *SignalFilter) GetDestinationChains() []string {
	if x != nil {
		return x.DestinationChains
	}
	return nil
}

func (x *SignalFilter) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *SignalFilter) GetMinConfidence() float64 {
	if x != nil {
		return x.MinConfidence
	}
	return 0
}

type Signal struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SignalType          string                 `protobuf:"bytes,2,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"`
	SourceChain         string                 `protobuf:"bytes,3,opt,name=source_chain,json=sourceChain,proto3" json:"source_chain,omitempty"`
	DestinationChain    string                 `protobuf:"bytes,4,opt,name=destination_chain,json=destinationChain,proto3" json:"destination_chain,omitempty"`
	Token               string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Amount              string                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	AmountUsd           float64                `protobuf:"fixed64,7,opt,name=amount_usd,json=amountUsd,proto3" json:"amount_usd,omitempty"`
	DetectedAt          int64                  `protobuf:"varint,8,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	EstimatedActionTime int64                  `protobuf:"varint,9,opt,name=estimated_action_time,json=estimatedActionTime,proto3" json:"estimated_action_time,omitempty"`
	Confidence          float64                `protobuf:"fixed64,10,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_proto_signal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{1}
}

func (x *Signal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Signal) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *Signal) GetSourceChain() string {
	if x != nil {
		return x.SourceChain
	}
	return ""
}

func (x *Signal) GetDestinationChain() string {
	if x != nil {
		return x.DestinationChain
	}
	return ""
}

func (x *Signal) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Signal) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Signal) GetAmountUsd() float64 {
	if x != nil {
		return x.AmountUsd
	}
	return 0
}

func (x *Signal) GetDetectedAt() int64 {
	if x != nil {
		return x.DetectedAt
	}
	return 0
}

func (x *Signal) GetEstimatedActionTime() int64 {
	if x != nil {
		return x.EstimatedActionTime
	}
	return 0
}

func (x *Signal) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Signal) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_signal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{2}
}

type ChainStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       string                 `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Connected     bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	LastBlock     uint64                 `protobuf:"varint,3,opt,name=last_block,json=lastBlock,proto3" json:"last_block,omitempty"`
	LastEventAt   int64                  `protobuf:"varint,4,opt,name=last_event_at,json=lastEventAt,proto3" json:"last_event_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainStatus) Reset() {
	*x = ChainStatus{}
	mi := &file_proto_signal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainStatus) ProtoMessage() {}

func (x *ChainStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainStatus.ProtoReflect.Descriptor instead.
func (*ChainStatus) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{3}
}

func (x *ChainStatus) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *ChainStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ChainStatus) GetLastBlock() uint64 {
	if x != nil {
		return x.LastBlock
	}
	return 0
}

func (x *ChainStatus) GetLastEventAt() int64 {
	if x != nil {
		return x.LastEventAt
	}
	return 0
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Chains         []*ChainStatus         `protobuf:"bytes,1,rep,name=chains,proto3" json:"chains,omitempty"`
	UptimeSeconds  int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	SignalsEmitted int64                  `protobuf:"varint,3,opt,name=signals_emitted,json=signalsEmitted,proto3" json:"signals_emitted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_signal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_signal_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetChains() []*ChainStatus {
	if x != nil {
		return x.Chains
	}
	return nil
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetSignalsEmitted() int64 {
	if x != nil {
		return x.SignalsEmitted
	}
	return 0
}

var File_proto_signal_proto protoreflect.FileDescriptor

const file_proto_signal_proto_rawDesc = "" +
	"\n" +
	"\x12proto/signal.proto\x12\x06oracle\"\xc4\x01\n" +
	"\fSignalFilter\x12!\n" +
	"\fsignal_types\x18\x01 \x03(\tR\vsignalTypes\x12#\n" +
	"\rsource_chains\x18\x02 \x03(\tR\fsourceChains\x12-\n" +
	"\x12destination_chains\x18\x03 \x03(\tR\x11destinationChains\x12\x16\n" +
	"\x06tokens\x18\x04 \x03(\tR\x06tokens\x12%\n" +
	"\x0emin_confidence\x18\x05 \x01(\x01R\rminConfidence\"\xc2\x03\n" +
	"\x06Signal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vsignal_type\x18\x02 \x01(\tR\n" +
	"signalType\x12!\n" +
	"\fsource_chain\x18\x03 \x01(\tR\vsourceChain\x12+\n" +
	"\x11destination_chain\x18\x04 \x01(\tR\x10destinationChain\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\tR\x06amount\x12\x1d\n" +
	"\n" +
	"amount_usd\x18\a \x01(\x01R\tamountUsd\x12\x1f\n" +
	"\vdetected_at\x18\b \x01(\x03R\n" +
	"detectedAt\x122\n" +
	"\x15estimated_action_time\x18\t \x01(\x03R\x13estimatedActionTime\x12\x1e\n" +
	"\n" +
	"confidence\x18\n" +
	" \x01(\x01R\n" +
	"confidence\x128\n" +
	"\bmetadata\x18\v \x03(\v2\x1c.oracle.Signal.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0f\n" +
	"\rStatusRequest\"\x89\x01\n" +
	"\vChainStatus\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\tR\achainId\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12\x1d\n" +
	"\n" +
	"last_block\x18\x03 \x01(\x04R\tlastBlock\x12\"\n" +
	"\rlast_event_at\x18\x04 \x01(\x03R\vlastEventAt\"\x8d\x01\n" +
	"\x0eStatusResponse\x12+\n" +
	"\x06chains\x18\x01 \x03(\v2\x13.oracle.ChainStatusR\x06chains\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12'\n" +
	"\x0fsignals_emitted\x18\x03 \x01(\x03R\x0esignalsEmitted2\x87\x01\n" +
	"\rOracleService\x12:\n" +
	"\x10SubscribeSignals\x12\x14.oracle.SignalFilter\x1a\x0e.oracle.Signal0\x01\x12:\n" +
	"\tGetStatus\x12\x15.oracle.StatusRequest\x1a\x16.oracle.StatusResponseB)Z'github.com/vaporif/x-chain-oracle/protob\x06proto3"

var (
	file_proto_signal_proto_rawDescOnce sync.Once
	file_proto_signal_proto_rawDescData []byte
)

func file_proto_signal_proto_rawDescGZIP() []byte {
	file_proto_signal_proto_rawDescOnce.Do(func() {
		file_proto_signal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signal_proto_rawDesc), len(file_proto_signal_proto_rawDesc)))
	})
	return file_proto_signal_proto_rawDescData
}

var file_proto_signal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_signal_proto_goTypes = []any{
	(*SignalFilter)(nil),   // 0: oracle.SignalFilter
	(*Signal)(nil),         // 1: oracle.Signal
	(*StatusRequest)(nil),  // 2: oracle.StatusRequest
	(*ChainStatus)(nil),    // 3: oracle.ChainStatus
	(*StatusResponse)(nil), // 4: oracle.StatusResponse
	nil,                    // 5: oracle.Signal.MetadataEntry
}
var file_proto_signal_proto_depIdxs = []int32{
	5, // 0: oracle.Signal.metadata:type_name -> oracle.Signal.MetadataEntry
	3, // 1: oracle.StatusResponse.chains:type_name -> oracle.ChainStatus
	0, // 2: oracle.OracleService.SubscribeSignals:input_type -> oracle.SignalFilter
	2, // 3: oracle.OracleService.GetStatus:input_type -> oracle.StatusRequest
	1, // 4: oracle.OracleService.SubscribeSignals:output_type -> oracle.Signal
	4, // 5: oracle.OracleService.GetStatus:output_type -> oracle.StatusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_signal_proto_init() }
func file_proto_signal_proto_init() {
	if File_proto_signal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signal_proto_rawDesc), len(file_proto_signal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_signal_proto_goTypes,
		DependencyIndexes: file_proto_signal_proto_depIdxs,
		MessageInfos:      file_proto_signal_proto_msgTypes,
	}.Build()
	File_proto_signal_proto = out.File
	file_proto_signal_proto_goTypes = nil
	file_proto_signal_proto_depIdxs = nil
}
